# Generated by Django 3.2.4 on 2021-08-03 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_auto_20210731_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='Lessons_per_month',
            new_name='lessons_per_month',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='Nationality',
            new_name='nationality',
        ),
    ]
