# Generated by Django 3.2.4 on 2021-07-30 12:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='age',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='Class_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='date_of_birth',
            new_name='Date_of_birth',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='last_name',
            new_name='First_name',
        ),
        migrations.AddField(
            model_name='student',
            name='Big_sister',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='District',
            field=models.CharField(default=-1.0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Email',
            field=models.EmailField(default=datetime.datetime(2021, 7, 30, 12, 54, 40, 434502, tzinfo=utc), max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Gender',
            field=models.CharField(choices=[('=M', 'Male'), ('K', 'Female'), ('O', 'Other')], default=datetime.datetime(2021, 7, 30, 12, 55, 5, 88751, tzinfo=utc), max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Guardian',
            field=models.CharField(default=datetime.datetime(2021, 7, 30, 12, 55, 51, 599717, tzinfo=utc), max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='ID_number',
            field=models.CharField(default=datetime.datetime(2021, 7, 30, 12, 55, 57, 435151, tzinfo=utc), max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Languages',
            field=models.CharField(choices=[('E', 'English'), ('K', 'Kiswahili'), ('O', 'Other')], default=datetime.datetime(2021, 7, 30, 12, 56, 2, 235076, tzinfo=utc), max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Laptop_serial',
            field=models.CharField(default=datetime.datetime(2021, 7, 30, 12, 56, 10, 246401, tzinfo=utc), max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Last_name',
            field=models.CharField(default=datetime.datetime(2021, 7, 30, 12, 56, 14, 935979, tzinfo=utc), max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Medical_report',
            field=models.FileField(default=datetime.datetime(2021, 7, 30, 12, 56, 19, 951100, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Mentors_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Nationality',
            field=models.CharField(choices=[('R', 'Rwandese'), ('K', 'Kenyan'), ('Su', 'Sudanesse'), ('S', 'Somali'), ('SS', 'South Sudanese')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Passport_number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Passport_photo',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Phone_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Room_number',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
